# 大模型配置
llms:
  - provider: openai
    model: gpt-4o-mini
    base_url: http://localhost:3000/v1
    api_key: sk-IIbJeDBOzGgWGGyZ0b64Ae6b61C84675B484825cE99c3c41
    timeout: 3000  # 超时时间 5 分钟
  - provider: deepseek
    model: deepseek-chat
    base_url: http://localhost:3000/v1
    api_key: sk-IIbJeDBOzGgWGGyZ0b64Ae6b61C84675B484825cE99c3c41
    timeout: 3000  # 超时时间 5 分钟

# prompt模板
prompt:
  paths:
    - core/prompt/prompts

# 鸿蒙 Harmony配置
harmony:
  toolkit:
    bin: D:/Devkits/Harmony/command-line-tools/bin
  template:
    base_dir: template


# RAG配置
rag:
  persist_directory: db/rag
  embedding:
    code:
      model: models/embedding/jina-embeddings-v2-base-code
    text:
      model: models/embedding/bge-m3
    rerank:
      model: models/embedding/bge-reranker-v2-m3

# database配置
db:
  url: sqlite+aiosqlite:///db/sqlite.db

# global state配置
state:
  android:
    project_dir: D:/Codes/Python/harmony-pilot/demos/bookdash
  harmony:
    project_dir: D:/Codes/Harmony/bookdash1