# 大模型配置
llms:
  - provider: openai
    model: gpt-4o-mini
    base_url: http://localhost:3000/v1
    api_key: sk-IIbJeDBOzGgWGGyZ0b64Ae6b61C84675B484825cE99c3c41
    timeout: 3000  # 超时时间 5 分钟
  - provider: deepseek
    model: deepseek-chat
    base_url: http://localhost:3000/v1
    api_key: sk-IIbJeDBOzGgWGGyZ0b64Ae6b61C84675B484825cE99c3c41
    timeout: 3000  # 超时时间 5 分钟


# 日志配置
logger:
  level: debug
  output: console
  format: "%(log_color)s%(asctime)s - %(name)s - %(levelname)s - %(message)s"


# prompt模板
prompt:
  paths:
    - core/prompt/prompts

# 鸿蒙配置
harmony:
  template:
    base_dir: template


# RAG配置
rag:
  embedding:
    code:
      model: models/embedding/jina-embeddings-v2-base-code
    text:
      model: models/embedding/jina-embeddings-v2-base-zh